# tells Travis that we will need to run in superuser mode
sudo: required

# tells travis to install Docker 
services:
  - docker

before_install:
  # below will run docker build pointing to particular Dockerfile.dev
  # it '.' at the end says build in regards to the context of the directory
  # '-t sahil68/client-test' will tag the image for travis to use once image is created
  # the below will run the image for client only and run tests below for it
  - docker build -t sahil68/client-test -f ./client/Dockerfile.dev ./client

# section below contain all the different commands that need to be executed to run the test suite
# series of commands that execute the tests
# "npm run test" overrides the default command when running the container
# travis CI watches the output of all these commands, 
# if it gets a status code other than 0, it assumes something wrong has happened and will error
script:
  # -e CI=true essentially stops and exists the test suite to return 0 status code to travis ci
  - docker run -e CI=true sahil68/client-test npm run test

#build prod images for all projects
after_success:
  - docker build -t sahil68/multi-client ./client
  - docker build -t sahil68/multi-nginx  ./nginx
  - docker build -t sahil68/multi-server ./server
  - docker build -t sahil68/multi-worker ./worker

#log in to docker CLI before we push stuff to docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

#now push all the prod images to docker hub
  - docker push sahil68/multi-client
  - docker push sahil68/multi-nginx
  - docker push sahil68/multi-server
  - docker push sahil68/multi-worker